### ISSUE TITLE
Macro Expansion Script

### ISSUE THREAD

**Issue by reem** [lihaoyi/macropy#62]
Some form of preprocessor script that could be run on files with macros to make them directly runnable by replacing all macro code with the actual generated code.

This would allow:
1. Packaging of scripts as directly runnable
2. Removal of macropy as a dependency for distributed code
3. Allows for macros to be used in projects that don't want another dependency as code-generation tools for individual developers

To take an example from the README:

point.py:

``` python
from macropy.case_classes import macros, case

@case
class Point(x, y): pass
```

CLI:

```
$ python expand_macros.py point.py
```

exp_point.py:

``` python
class Point(object):
    __slots__ = ['x', 'y']
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __str__(self):
        return "Point(" + self.x + ", " + self.y + ")"

    def __repr__(self):
        return self.__str__()

    def __eq__(self, other):
        return self.x == other.x and self.y == other.y

    def __ne__(self, other):
        return not self.__eq__(other)

    def __iter__(self, other):
        yield self.x
        yield self.y
```

I for one would love to be able to use macros like this to generate boilerplate code but still maintain my scripts as directly runnable and easily distributable.

**Comment by azazel75** [comment]
Nothing had come up since 2013, so I'm closing this
