### ISSUE TITLE
quick lambda execution error in python 2.7.9

### ISSUE THREAD

**Issue by zhizhongzhiwai** [lihaoyi/macropy#76]
from macropy.quick_lambda import macros, f, _

print map(f[_ + 1], [1, 2, 3])    # [2, 3, 4]  
print reduce(f[_ \* _], [1, 2, 3]) # 6      

get error:
TypeError: unsupported operand type(s) for +: 'function' and 'int'

**Comment by azazel75** [comment]
This work with minor changes with current master and Py3.6

**Comment by EkremDincel** [comment]
It does not work on Python3.8, same exception. If it doens't support Python3.8, why this is in the PyPi page:
MacroPy3 is tested to run on __CPython 3.4 or newer__ and PyPy 3.5. I has no current support for Jython.
