### ISSUE TITLE
How should I cite macropy?

### ISSUE THREAD

**Issue by alexbw** [lihaoyi/macropy#89]
I would like to reference macropy in a scientific publication. How should I best do this?

**Comment by azazel75** [comment]
>>>>> "Alex" == Alex Wiltschko <notifications@github.com> writes:

    Alex> I would propose
    Alex> @online{macropy,
    Alex>   author = {Haoyi, Li},
    Alex>   title = {MacroPy},
    Alex>   url = {https://github.com/lihaoyi/macropy},
    Alex>   urldate = {2018-09-25}
    Alex> }

+1

go for it!

**Comment by jnhnum1** [comment]
I would also include myself (Justin Holmgren) as the second author, as in
the "Project Details" section at
https://pypi.org/project/MacroPy/#data
(Macropy was originally a class project of Haoyi and me, and he continued
afterwards to improve and maintain it more than I did)

**Comment by alexbw** [comment]
You got it!
