### ISSUE TITLE
Python 3.4 version requirement in setup.py too strict?

### ISSUE THREAD

**Issue by anentropic** [lihaoyi/macropy#99]
The readme says:

> MacroPy3 is tested to run on CPython 3.4 or newer

If I try to add latest `macropy3` to my Python 3.7 project using `poetry` I get:

```
[SolverProblemError]
The current project's Python requirement (>=3.7) is not compatible with some of the required packages Python requirement:
  - macropy3 requires Python ~=3.4

Because macropy3 (1.1.0b2) requires Python ~=3.4
 and no versions of macropy3 match >1.1.0-beta.2,<2.0.0, macropy3 is forbidden.
So, because fineprint depends on macropy3 (^1.1.0-beta.2), version solving failed.
```

I can see your Travis-CI is testing against 3.4, 3.5, 3.6, 3.7 and PyPy 3.5, all passing.

So I think the problem is just that `python_requires='~=3.4'` in your `setup.py` is too strict.

**Comment by azazel75** [comment]
of course you're right! I need to find the time tomake a release! Thanks

**Comment by anentropic** [comment]
please make a release 🙏  😃
